route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:465'
        auth_username: 'saraulantur@gmail.com'
        auth_identity: "saraulantur@gmail.com"
        auth_password: "henangoggzslrpjj"
        from: 'saraulantur@gmail.com'
        to: 'edige.mazhit.2004@gmail.com'
